ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "dimensionWidth" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "dimensionHeight" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "availableSizes" TEXT NOT NULL DEFAULT '[]';
