ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "pricingMode" TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "otherCharges" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "gstPercent" DOUBLE PRECISION NOT NULL DEFAULT 3;
ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "manualPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
